### ISSUE TITLE
multithreading on macos

### ISSUE THREAD

**Issue by djrecipe** [avolvemark/ironpdf-test#1]
Thanks for the example!

Multithreaded rendering and in general web apps hosted on a Mac currently have some issues with IronPdf. We're looking into ways to improve IronPdf on Mac but major improvements for Mac web apps are probably still a couple months away.

_Longer explanation_

IronPdf uses Chrome to convert html to pdfs. Chromium embedded framework's native codebase and limitations are significantly different for Mac than they are for Linux and Windows. There are two major limitations on Mac:

- true concurrent multithreading is much harder to implement, although it is possible
- you cannot let the original thread which CEF was initialized on to die - this causes issues in Mac web environments where threads are spawned and die as needed

Typically Macs are not production environments for web servers (as much as Linux and Windows) so this hasn't been as high of a priority, although we recognize these are some annoying limitations. A fix for multithreading is feasible from our end and is being worked on. A fix for the second issue is slightly more difficult for us to implement. 

On MacOs, you may find better luck calling `Installation.Initialize()` on a main thread you know will not die and also avoiding concurrent renders. Again, I know this is not ideal, but its somewhat of a workaround for the current state of things.

**Comment by avolvemark** [comment]
@djrecipe - thanks for the followup!  I'll give your suggestions a shot but the obvious workaround is to develop this stuff on something other than a Mac.

All of our prod services are on Linux and most of our developers are on Windows.  I'm the only person using a Mac for development on the dotnet side so the impact is minimal (but frustrating for dev experience).  Sounds like we'll need to use Windows/Linux to develop the services utilizing IronPDF and run those via an x64 Linux container on the ARM Macs.
